project_name: gomicro

builds:
  - id: linux-amd64
    binary: '{{.ProjectName}}_{{.Os}}_{{.Arch}}'
    main: ./cmd
    goos:
      - linux
    goarch:
      - amd64
    no_unique_dist_dir: true

  - id: darwin-amd64
    binary: '{{.ProjectName}}_{{.Os}}_{{.Arch}}'
    main: ./cmd
    goos:
      - darwin
    goarch:
      - amd64
    no_unique_dist_dir: true

  - id: windows-amd64
    binary: '{{.ProjectName}}_{{.Os}}_{{.Arch}}'
    main: ./cmd
    goos:
      - windows
    goarch:
      - amd64
    no_unique_dist_dir: true

archives:
  - format: binary
    name_template: '{{.ProjectName}}_{{.Os}}_{{.Arch}}'

checksum:
  name_template: '{{.ProjectName}}_checksums.txt'
