version: '3'

volumes:
  db:

services:
  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}

  gomicro:
    image: ghcr.io/sirjager/gomicro:latest
    container_name: gomicro
    depends_on:
      - db
    ports:
      - 4420
      - 4424
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASS=${DATABASE_PASS}
      - DB_DRIVER=postgres
      - DB_ARGS=?sslmode=disable
      - DB_MIGRATE=file://./migrate/postgres
      - GMAIL_NAME=${GMAIL_NAME}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
    entrypoint: ['/app/wait-for.sh', 'db:5432', '--', '/app/start.sh']
    command: ['/app/main']
