version: '3'

volumes:
  gomicro_db:
  gomicro_redis:

services:
  gomicro_redis:
    container_name: gomicro_redis
    image: redis:latest
    volumes:
      - gomicro_redis:/data

  gomicro_db:
    container_name: gomicro_db
    image: postgres:14-alpine
    volumes:
      - gomicro_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  gomicro:
    image: ghcr.io/sirjager/gomicro:latest
    container_name: gomicro
    depends_on:
      - gomicro_db
      - gomicro_redis
    ports:
      - 4420
      - 4421
    environment:
      - DB_HOST=gomicro_db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_DRIVER=postgres
      - DB_ARGS=?sslmode=disable
      - DB_MIGRATE=./migrations
      - GMAIL_NAME=${GMAIL_NAME}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - REDIS_ADDR=gomicro_redis:6379
    entrypoint: ['/app/wait-for.sh', 'gomicro_db:5432', '--', '/app/start.sh']
    command: ['/app/main']
