// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	// account id
	ID uuid.UUID `json:"id"`
	// unique email address
	Email string `json:"email"`
	// unique username
	Username string `json:"username"`
	// hashed password
	Password string `json:"password"`
	// first name
	Firstname string `json:"firstname"`
	// last name
	Lastname string `json:"lastname"`
	// email verified status
	EmailVerified bool `json:"email_verified"`
	// short lived email verification token
	VerifyToken string `json:"verify_token"`
	// last verification token sent at timestamp
	LastVerifySentAt time.Time `json:"last_verify_sent_at"`
	// short lived password recovery token
	RecoveryToken string `json:"recovery_token"`
	// last password recovery token sent at timestamp
	LastRecoverySentAt time.Time `json:"last_recovery_sent_at"`
	// short lived email change token
	EmailchangeToken string `json:"emailchange_token"`
	// last change email token sent at timestamp
	LastEmailchangeSentAt time.Time `json:"last_emailchange_sent_at"`
	// list of all allowed ip address to access this row
	AllowedIps []string `json:"allowed_ips"`
	// short lived allowip token for allowing new ipaddress
	AllowipToken string `json:"allowip_token"`
	// short lived account deletion token
	DeleteToken string `json:"delete_token"`
	// last deletion token sent at timestamp
	LastDeleteSentAt time.Time `json:"last_delete_sent_at"`
	// created at timestamp
	CreatedAt time.Time `json:"created_at"`
	// last updated at timestamp
	UpdatedAt time.Time `json:"updated_at"`
}
